baseURL = "/"
languageCode = "en-us"
title = "Jake's Pages"
theme = "anatole"
copyright = "Work of Jacob Logemann. All rights reserved."
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildExpired = false
buildFuture = false
defaultContentLanguage = "en"
googleAnalytics = "G-ZQ19LB23FP"
disableHugoGeneratorInject = true
disableKinds = ["RSS"]

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Notes"
  weight = 200
  identifier = "notes"
  url = "/notes/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.parser]
attribute = true
autoHeadingID = true
autoHeadingIDType = "github"
[markup.goldmark.renderer]
hardWraps = false
unsafe = false
xhtml = false
[markup.highlight]
anchorLineNos = true
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 2
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2


[params]
title = "Jake's Pages"
author = "Jacob Logemann"
description = "Just call me Jake"
profilePicture = "images/profile.png"
displayMode = "dark"
doNotLoadAnimations = false # Animations are loaded by default
singleDateFormat = "Mon, Jan 2, 2006"
indexDateFormat = "Mon, Jan 2, 2006"
listDateFormat = "Jan 2"
pygmentsCodeFences = true
pygmentsUseClasses = true
customCss = ["css/tweaks.css", "css/syntax.css", "fontawesome/css/svg-with-js.min.css"]
customJs = ["fontawesome/js/all.min.js"]
digitaloceanReferralLink = "https://m.do.co/c/7201eed99612"

[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".
