name: Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  pages:
    runs-on: ubuntu-latest

    concurrency:
      cancel-in-progress: true
      group: "pages"

    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: build
        uses: jakelogemann/images/tools@release
        with:
          entrypoint: hugo
          args: --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
